// Starter Proto file, feel free to change name of the file

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: protos/cm_worker.proto

package kvstore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Define the error proto here
type KvError int32

const (
	KvError_kNoError     KvError = 0
	KvError_kKeyNotFound KvError = 1
	KvError_kTimeout     KvError = 2
)

// Enum value maps for KvError.
var (
	KvError_name = map[int32]string{
		0: "kNoError",
		1: "kKeyNotFound",
		2: "kTimeout",
	}
	KvError_value = map[string]int32{
		"kNoError":     0,
		"kKeyNotFound": 1,
		"kTimeout":     2,
	}
)

func (x KvError) Enum() *KvError {
	p := new(KvError)
	*p = x
	return p
}

func (x KvError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KvError) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_cm_worker_proto_enumTypes[0].Descriptor()
}

func (KvError) Type() protoreflect.EnumType {
	return &file_protos_cm_worker_proto_enumTypes[0]
}

func (x KvError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KvError.Descriptor instead.
func (KvError) EnumDescriptor() ([]byte, []int) {
	return file_protos_cm_worker_proto_rawDescGZIP(), []int{0}
}

// TODO: Let value just not be string, we can have a oneof field in the proto.
type PutKeyInternalArg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required, Key value to store in kvstore
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Required, Value to store in kvstore.
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutKeyInternalArg) Reset() {
	*x = PutKeyInternalArg{}
	mi := &file_protos_cm_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutKeyInternalArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutKeyInternalArg) ProtoMessage() {}

func (x *PutKeyInternalArg) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cm_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutKeyInternalArg.ProtoReflect.Descriptor instead.
func (*PutKeyInternalArg) Descriptor() ([]byte, []int) {
	return file_protos_cm_worker_proto_rawDescGZIP(), []int{0}
}

func (x *PutKeyInternalArg) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutKeyInternalArg) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PutKeyInternalRet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorStatus   KvError                `protobuf:"varint,2,opt,name=error_status,json=errorStatus,proto3,enum=main.KvError" json:"error_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutKeyInternalRet) Reset() {
	*x = PutKeyInternalRet{}
	mi := &file_protos_cm_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutKeyInternalRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutKeyInternalRet) ProtoMessage() {}

func (x *PutKeyInternalRet) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cm_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutKeyInternalRet.ProtoReflect.Descriptor instead.
func (*PutKeyInternalRet) Descriptor() ([]byte, []int) {
	return file_protos_cm_worker_proto_rawDescGZIP(), []int{1}
}

func (x *PutKeyInternalRet) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PutKeyInternalRet) GetErrorStatus() KvError {
	if x != nil {
		return x.ErrorStatus
	}
	return KvError_kNoError
}

type GetKeyInternalArg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Key to fetch the data from KvStore.
	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyInternalArg) Reset() {
	*x = GetKeyInternalArg{}
	mi := &file_protos_cm_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyInternalArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyInternalArg) ProtoMessage() {}

func (x *GetKeyInternalArg) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cm_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyInternalArg.ProtoReflect.Descriptor instead.
func (*GetKeyInternalArg) Descriptor() ([]byte, []int) {
	return file_protos_cm_worker_proto_rawDescGZIP(), []int{2}
}

func (x *GetKeyInternalArg) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetKeyInternalRet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorStatus   KvError                `protobuf:"varint,2,opt,name=error_status,json=errorStatus,proto3,enum=main.KvError" json:"error_status,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyInternalRet) Reset() {
	*x = GetKeyInternalRet{}
	mi := &file_protos_cm_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyInternalRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyInternalRet) ProtoMessage() {}

func (x *GetKeyInternalRet) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cm_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyInternalRet.ProtoReflect.Descriptor instead.
func (*GetKeyInternalRet) Descriptor() ([]byte, []int) {
	return file_protos_cm_worker_proto_rawDescGZIP(), []int{3}
}

func (x *GetKeyInternalRet) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetKeyInternalRet) GetErrorStatus() KvError {
	if x != nil {
		return x.ErrorStatus
	}
	return KvError_kNoError
}

func (x *GetKeyInternalRet) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_protos_cm_worker_proto protoreflect.FileDescriptor

const file_protos_cm_worker_proto_rawDesc = "" +
	"\n" +
	"\x16protos/cm_worker.proto\x12\x04main\";\n" +
	"\x11PutKeyInternalArg\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"_\n" +
	"\x11PutKeyInternalRet\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x120\n" +
	"\ferror_status\x18\x02 \x01(\x0e2\r.main.KvErrorR\verrorStatus\"%\n" +
	"\x11GetKeyInternalArg\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"u\n" +
	"\x11GetKeyInternalRet\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x120\n" +
	"\ferror_status\x18\x02 \x01(\x0e2\r.main.KvErrorR\verrorStatus\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value*7\n" +
	"\aKvError\x12\f\n" +
	"\bkNoError\x10\x00\x12\x10\n" +
	"\fkKeyNotFound\x10\x01\x12\f\n" +
	"\bkTimeout\x10\x022\x9c\x01\n" +
	"\x0eKvStoreService\x12D\n" +
	"\x0ePutKeyInternal\x12\x17.main.PutKeyInternalArg\x1a\x17.main.PutKeyInternalRet\"\x00\x12D\n" +
	"\x0eGetKeyInternal\x12\x17.main.GetKeyInternalArg\x1a\x17.main.GetKeyInternalRet\"\x00B\fZ\n" +
	"./;kvstoreb\x06proto3"

var (
	file_protos_cm_worker_proto_rawDescOnce sync.Once
	file_protos_cm_worker_proto_rawDescData []byte
)

func file_protos_cm_worker_proto_rawDescGZIP() []byte {
	file_protos_cm_worker_proto_rawDescOnce.Do(func() {
		file_protos_cm_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_cm_worker_proto_rawDesc), len(file_protos_cm_worker_proto_rawDesc)))
	})
	return file_protos_cm_worker_proto_rawDescData
}

var file_protos_cm_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_cm_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_cm_worker_proto_goTypes = []any{
	(KvError)(0),              // 0: main.KvError
	(*PutKeyInternalArg)(nil), // 1: main.PutKeyInternalArg
	(*PutKeyInternalRet)(nil), // 2: main.PutKeyInternalRet
	(*GetKeyInternalArg)(nil), // 3: main.GetKeyInternalArg
	(*GetKeyInternalRet)(nil), // 4: main.GetKeyInternalRet
}
var file_protos_cm_worker_proto_depIdxs = []int32{
	0, // 0: main.PutKeyInternalRet.error_status:type_name -> main.KvError
	0, // 1: main.GetKeyInternalRet.error_status:type_name -> main.KvError
	1, // 2: main.KvStoreService.PutKeyInternal:input_type -> main.PutKeyInternalArg
	3, // 3: main.KvStoreService.GetKeyInternal:input_type -> main.GetKeyInternalArg
	2, // 4: main.KvStoreService.PutKeyInternal:output_type -> main.PutKeyInternalRet
	4, // 5: main.KvStoreService.GetKeyInternal:output_type -> main.GetKeyInternalRet
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_cm_worker_proto_init() }
func file_protos_cm_worker_proto_init() {
	if File_protos_cm_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_cm_worker_proto_rawDesc), len(file_protos_cm_worker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_cm_worker_proto_goTypes,
		DependencyIndexes: file_protos_cm_worker_proto_depIdxs,
		EnumInfos:         file_protos_cm_worker_proto_enumTypes,
		MessageInfos:      file_protos_cm_worker_proto_msgTypes,
	}.Build()
	File_protos_cm_worker_proto = out.File
	file_protos_cm_worker_proto_goTypes = nil
	file_protos_cm_worker_proto_depIdxs = nil
}
