// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package kvstore

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KvStoreServiceClient is the client API for KvStoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KvStoreServiceClient interface {
	PutKeyInternal(ctx context.Context, in *PutKeyInternalArg, opts ...grpc.CallOption) (*PutKeyInternalRet, error)
	GetKeyInternal(ctx context.Context, in *GetKeyInternalArg, opts ...grpc.CallOption) (*GetKeyInternalRet, error)
}

type kvStoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKvStoreServiceClient(cc grpc.ClientConnInterface) KvStoreServiceClient {
	return &kvStoreServiceClient{cc}
}

func (c *kvStoreServiceClient) PutKeyInternal(ctx context.Context, in *PutKeyInternalArg, opts ...grpc.CallOption) (*PutKeyInternalRet, error) {
	out := new(PutKeyInternalRet)
	err := c.cc.Invoke(ctx, "/main.KvStoreService/PutKeyInternal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvStoreServiceClient) GetKeyInternal(ctx context.Context, in *GetKeyInternalArg, opts ...grpc.CallOption) (*GetKeyInternalRet, error) {
	out := new(GetKeyInternalRet)
	err := c.cc.Invoke(ctx, "/main.KvStoreService/GetKeyInternal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KvStoreServiceServer is the server API for KvStoreService service.
// All implementations must embed UnimplementedKvStoreServiceServer
// for forward compatibility
type KvStoreServiceServer interface {
	PutKeyInternal(context.Context, *PutKeyInternalArg) (*PutKeyInternalRet, error)
	GetKeyInternal(context.Context, *GetKeyInternalArg) (*GetKeyInternalRet, error)
	mustEmbedUnimplementedKvStoreServiceServer()
}

// UnimplementedKvStoreServiceServer must be embedded to have forward compatible implementations.
type UnimplementedKvStoreServiceServer struct {
}

func (UnimplementedKvStoreServiceServer) PutKeyInternal(context.Context, *PutKeyInternalArg) (*PutKeyInternalRet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutKeyInternal not implemented")
}
func (UnimplementedKvStoreServiceServer) GetKeyInternal(context.Context, *GetKeyInternalArg) (*GetKeyInternalRet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeyInternal not implemented")
}
func (UnimplementedKvStoreServiceServer) mustEmbedUnimplementedKvStoreServiceServer() {}

// UnsafeKvStoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KvStoreServiceServer will
// result in compilation errors.
type UnsafeKvStoreServiceServer interface {
	mustEmbedUnimplementedKvStoreServiceServer()
}

func RegisterKvStoreServiceServer(s grpc.ServiceRegistrar, srv KvStoreServiceServer) {
	s.RegisterService(&KvStoreService_ServiceDesc, srv)
}

func _KvStoreService_PutKeyInternal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutKeyInternalArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvStoreServiceServer).PutKeyInternal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.KvStoreService/PutKeyInternal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvStoreServiceServer).PutKeyInternal(ctx, req.(*PutKeyInternalArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _KvStoreService_GetKeyInternal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyInternalArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvStoreServiceServer).GetKeyInternal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.KvStoreService/GetKeyInternal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvStoreServiceServer).GetKeyInternal(ctx, req.(*GetKeyInternalArg))
	}
	return interceptor(ctx, in, info, handler)
}

// KvStoreService_ServiceDesc is the grpc.ServiceDesc for KvStoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KvStoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.KvStoreService",
	HandlerType: (*KvStoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutKeyInternal",
			Handler:    _KvStoreService_PutKeyInternal_Handler,
		},
		{
			MethodName: "GetKeyInternal",
			Handler:    _KvStoreService_GetKeyInternal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/cm_worker.proto",
}
